# [Info]
site_name: xcluo的个人仓库           # 网页标签名
site_url: https://xcluo.github.io   # 个人网页的url域名
site_author: xcluo
site_description: xcluo的个人仓库
use_directory_urls: false           # 所有的页面链接都以`.html`文件的形式，使引用相对链接资源成立


# [Navigtion]
nav:
  - Blog:   # 直接在该行 blog/index.md，左侧将不会展示日期归档（archive）和分类（categories）
    - blog/index.md
  - AI:
    - 专业名词: AI/annotation.md
    - 训练总览: AI/Train_Overview/index.md
    - AI_Lab: AI/AI_Lab/AI_Lab.md
    - 功能实现:
      - 论文笔记: 
        - 语言模型: AI/Paper_Reading/LM/LMs/index.md  
        - 强化学习: AI/Paper_Reading/LM/Reinforcement_Learning/index.md  
        - 搜索推荐: AI/Paper_Reading/LM/Search_Recommender/index.md  
        - 模型种类: AI/Paper_Reading/LM/Model_Category/index.md  
        - 架构分析: AI/Paper_Reading/LM/Model_Analysis/index.md  
      - 基本组件: 
        - Tokenizer: AI/Paper_Reading/Component/Tokenizer/index.md
        - Embedding: AI/Paper_Reading/Component/Embedding/embedding.md
        - Normlization: AI/Paper_Reading/Component/Normalization/normalization.md
        - Optimizer: AI/Paper_Reading/Component/Optimizer/optimizer.md
        - HyperParameter: AI/Paper_Reading/Component/HyperParameter/index.md
        - Activation: AI/Paper_Reading/Component/Activation/activation.md
      - 炼丹技巧: AI/Paper_Reading/Trick/trick.md
    - 数据指标: AI/Metrics/index.md
    - 机器学习库: AI/AI_Platform/index.md
      # - Tensorflow: AI/AI_Platform/Tensorflow/index.md
      # - PyTorch: AI/AI_Platform/PyTorch/index.md
      # - Transformers: AI/AI_Platform/Transformers/index.md
      # - PaddlePaddle: AI/AI_Platform/PaddlePaddle/index.md
      # - Nvidia: AI/AI_Platform/Nvidia/index.md

  - 数学:
    - 专业名词: Math/annotation.md
    - 线性代数: Math/Linear_Algebra/index.md
    - 微积分: Math/Calculus/index.md
    
  
  - 编程语言:
    - Java: Programing/Java/index.md
    - Python: Programing/Python/index.md
    - Shell:
      - Bash: Programing/Shell/Bash/index.md
      - PowerShell: Programing/Shell/PowerShell/index.md
    - Git: Programing/Git/index.md
    - HTML:
      - html: Programing/HTML/html/index.md
      - CSS: Programing/HTML/CSS/index.md
    - Tex:
      - Latex: Programing/Tex/Latex/index.md
      - Markdown: Programing/Tex/Markdown/index.md
      - MkDocs: Programing/Tex/MkDocs/index.md
    - FTP: 
      - LFTP: Programing/FTP/LFTP/index.md
    - MATLAB: Programing/MATLAB/index.md
    - SQL: Programing/SQL/index.md
    - Algorithm: Programing/Algorithm/index.md
    - 轮子: Programing/wheel/index.md
    - 容器:
      - Docker: Programing/Container/Docker/index.md
      - K8s: Programing/Container/K8s/index.md

  - 软件:
    - 集成开发环境:
      - IDEA: Software/IDE/IDEA/index.md
      - PyCharm: Software/IDE/PyCharm/index.md
      - VSCode: Software/IDE/VSCode/index.md
    - 编译环境:
      - Conda: Software/Compiler/Conda/index.md
      - CUDA: Software/Compiler/CUDA/index.md
      - Maven: Software/Compiler/Maven/index.md
    - 办公软件:
      - Office: Software/Office/Office/index.md
      - Adboe: Software/Office/Adobe/index.md
   
  - 系统:
    - Linux: System/Linux/index.md
    - Windows: System/Windows/index.md
    - 虚拟机: System/Virtual_Machine/index.md

  - 资源:
    - 多媒体: Resource/Media/index.md
    - 工具: Resource/Tool/index.md
    - 手册: Resource/Tutorial/index.md

  - 杂项:
    - 酒: MISC/Wine/index.md
    - 车: MISC/Car/index.md
    - 衣服: MISC/Clothes/index.md
    - 鞋子: MISC/Shoe/index.md
    - 棋牌:
      - 棋: MISC/Chess_Cards/Chess.md
      - 牌: MISC/Chess_Cards/Cards.md
      - 麻将: MISC/Chess_Cards/Mahjong.md
      - 牌九: MISC/Chess_Cards/PaiGow.md

# [UI]界面

## [top] 顶部栏
theme:
  name: material
  custom_dir: overrides
  # custom_dir: packages/stylesheets/custom_css         # 自定义主题文件夹
  
  # 主题色板，色板主题执行列表循环切换，可不止2个
  palette:
    - scheme: default           # 缺省日间模式
      primary: green            # 顶部颜色
      accent: orange            # 鼠标移动至链接等可交互元件的高亮显示颜色
      toggle:
        icon: material/weather-night    
                                # 当前模式图标
        name: 切换至夜间模式     # 鼠标悬浮提示

    - scheme: slate             # 切换夜间模式
      primary: grey             # 顶部颜色
      accent: orange            # 鼠标移动至链接等可交互元件的高亮显示颜色
      toggle:
        icon: material/weather-sunny   
                                # 当前模式图标
        name: 切换至日间模式     # 鼠标悬浮提示
    

  features:
    - navigation.tabs     # 显示顶部导航栏
    # - navigation.tabs.sticky   
                          # enable: 页面超过顶部导航栏时导航栏常驻显示
                          # disable: 页面超过顶部导航栏时导航栏不再显示
    - navigation.top      # 网页上滑出现【回到页面顶部】按钮


    # - navigation.expand   # enable: 左侧分级目录缺省全部展开
                            # disable: 左侧分级目录缺省全部折叠
    # - navigation.sections # enable: 左侧分级目录不缩进显示
                            # disable: 左侧分级目录缩进显示

    # - toc.integrate       # enable: 网页内容分级目录合并入左侧分级目录；
                            # disable: 右侧自动生成网页内容分级目录。

    - navigation.indexes  # 打开目录下的index.md，而不是第一篇文章
    - navigation.path     # 页面上部出现文件目录路径
    
    - search.suggest      # 搜索输入一些内容时会联想要输入的内容进行推荐显示
    - search.highlight    # 搜索出的关键词进行高亮显示
    # - search.share        # 搜索框输入内容后出现分享按钮

    - content.code.copy   # 网页代码块内容区域出现代码复制按钮
    - content.action.edit # 网页中显示编辑按钮, 点击按钮跳转到编辑页面
                          # 需要结合 edit_uri 一起使用

  language: zh # 一些提示性的文字会变成中文

  icon:
    repo: fontawesome/brands/github
                          # 定义右上角github图标
    
    admonition:   
      # 替换icons https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons-octicons
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

edit_uri: edit/main/docs  # 点击编辑按钮跳转的链接


## [top-right corner] 右上角落
repo_url: https://github.com/xcluo/xcluo.github.io  # 右上角点击跳转的链接
repo_name: xcluo.github.io                          # 右上角显示的名字

 
## [bottom-left corner] 左下角落
copyright: Powered by xcluo                         # 版权声明


## [bottom-right corner] 右下角落
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/
      name: Bilibili                                # 鼠标悬浮提示文本
    - icon: fontawesome/brands/github
      link: https://github.com/xcluo
      name: GitHub | xcluo                          # 鼠标悬浮提示文本
  


# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
      # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      # 支持语种表：https://squidfunk.github.io/mkdocs-material/plugins/search/
      lang:
        - en
        - en
      separator: '[\s\u200b\-\u3000\u3001\u3002\uFF0C\uFF0E\uFF1F\uFF01\uFF1B]+'                     # 安装jieba后才生效中文搜索
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - glightbox
  - blog:    # 要求 mkdocs-material >= 9.2.0b3
      # blog relate #
      blog_dir: blog            # 对应占位符  `blog`
      # blog_toc: true        # table of content

      # post related #
      post_dir: "{blog}/posts"  # 指定 posts 目录路径
      post_url_date_format: yyyy/MM/dd  # 对应占位符 `date`， yyyy/MM/dd，也可通过metadata.date指定
      post_url_format: "{date}/{slug}"  # 指定 post的路径格式为 `{date}/{slug}`，后者也可通过metadate.slug指定
                                        # 也可直接{slug}
      
      post_date_format: medium  # 指定时间格式{full, ^^long^^, medium, short}
      post_excerpt: required    # 强制要求定义摘要内容，通过 <!-- more --> 分割摘要与全文
      post_excerpt_separator: <!-- more -->
                                # 指定摘要的分隔符
      
      post_readtime: true       # 元信息中显示post所需阅读时间，对应占位符`readtime`,也可通过metadata.readtime指定
      # post_readtime_words_per_minute: 265  # 指定post每分钟阅读的字数

      # draft: true
      # draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      
      # categories related #
      categories: true
      # categories_toc: true
      
      # archive related #
      archive: true
      archive_name: 归档             # 指定总归档名
      archive_date_format: yyyy-MM   # 归档分支粒度显示格式
      archive_url_date_format: yyyy-MM
                                     # 归档分支别名（以date为依据）
      archive_url_format: "archive/{date}"
                                     # 归档分支url路径
      pagination_per_page: 10  # 指定归档分支每页最多显示的post数
      # pagination_url_format: "page/{page}"

  # - document-dates:            # pip install mkdocs-document-dates
  #     position: top         # 显示位置: {^^bottom^^, top}
  #     type: date               # Date type: date  datetime  timeago, default: date
  #     locale: zh               # Localization: en zh zh_TW es fr de ar ja ko ru, default: en
  #     date_format: '%Y-%m-%d'  # Date format strings, e.g., %Y-%m-%d, %b %d, %Y, etc
  #     time_format: '%H:%M:%S'  # Time format strings (valid only if type=datetime)
  #     show_author: false
  #     recently-updated: true   # Show recently updated date


markdown_extensions:
  - attr_list
  - pymdownx.tasklist:        # todo list
      custom_checkbox: true
  - md_in_html
  - pymdownx.arithmatex:      # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置

  # 代码块特征设置
  - pymdownx.superfences      # enable代码设置
  - pymdownx.snippets         # 导入外部文件资源
  - pymdownx.inlinehilite     # 行内代码高亮，https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.highlight:
      # linenums: true          # 代码块中显示代码行号
      # auto_title: true        # 自动为代码块添加标题
      use_pygments: true        # 使用pygments渲染代码块内容
  
  # 增加内容目录，如同一个block有不同的代码类型
  - pymdownx.tabbed:            # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
      alternate_style: true     

  - pymdownx.caret              # enable上标符号^
                                  # - 下划线：^^xx^^
                                  # - 上标：^X^
  - pymdownx.mark               # enable等号=，
                                  # - 高亮：==xx==
  - pymdownx.tilde              # enable波浪线符号~
                                  # - 删除线：~~xx~~
                                  # - 下标：~x~
  - pymdownx.critic             # enable大括号{}，https://github.com/CriticMarkup/CriticMarkup-toolkit
                                  # - 下划线：{++ ++}
                                  # - 删除线：{-- --}
                                  # - 将A替换为B，A删除线B下划线：{~~A~>B~~}
                                  # - 注释：{>> <<}
                                  # - 高亮：{== ==}
  - pymdownx.keys               # enabel加号~
                                  # - 将内容变成按键：++x++
                                  # - ↑ 仅限键盘按键名的小写

  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要



extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - packages/mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  # katex
  - packages/mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js


extra_css:
  # - packages/mkdocs/css/no-footer.css # 不使用底部的翻页
  # - packages/mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - packages/stylesheets/css/extra_img.css            # image.css
  - packages/stylesheets/css/extra_font.css           # font.css
  - packages/stylesheets/css/extra_component.css      # component.css
  # - packages/stylesheets/css/extra_main.css           # main.css
  - packages/stylesheets/css/extra_code.css           # code.css


extra_templates:
  - packages/stylesheets/extra.html