# [Info]
site_name: xcluo的个人仓库           # 网页标签名
site_url: https://xcluo.github.io   # 个人网页的url域名
site_author: xcluo
site_description: xcluo的个人仓库


# [Navigtion]
nav:
  - AI:
    - AI_Lab: AI/AI_Lab/AI_Lab.md
    - 论文笔记:
      - 语言模型: AI/Paper_Reading/LM/index.md
      - 基本组件: 
        - Tokenizer: AI/Paper_Reading/Component/Tokenizer/index.md
        - Embedding:
          - Position Embedding: AI/Paper_Reading/Component/Embedding/Position_Embedding/index.md
      - 炼丹技巧: 
        - 显存优化: AI/Paper_Reading/Trick/Memory_Saving/index.md
    - 评判指标: AI/Metrics/metrics.md
    - 机器学习库:
      - Tensorflow: AI/AI_Platform/Tensorflow/index.md
      - PyTorch: AI/AI_Platform/PyTorch/index.md
      - Transformers: AI/AI_Platform/Transformers/index.md
      - PaddlePaddle: AI/AI_Platform/PaddlePaddle/index.md
    
  
  - 编程语言:
    - Java: Programing/Java/index.md
    - Python: Programing/Python/index.md
    - Shell:
      - Bash: Programing/Shell/Bash/index.md
      - PowerShell: Programing/Shell/PowerShell/index.md
    - Git: Programing/Git/index.md
    - FTP: Programing/FTP/index.md
    - MATLAB: Programing/MATLAB/index.md
    - Latex: Programing/Latex/index.md
    - Markdown: Programing/Markdown/index.md
    - SQL: Programing/SQL/index.md
    - MkDocs: Programing/MkDocs/index.md
    - 轮子: Programing/wheel/index.md

  - 软件:
    - 集成开发环境:
      - IDEA: Software/IDE/IDEA/index.md
      - PyCharm: Software/IDE/PyCharm/index.md
      - VSCode: Software/IDE/VSCode/index.md
    - 编译环境:
      - Conda: Software/Compiler/Conda/index.md
      - CUDA: Software/Compiler/CUDA/index.md
      - Maven: Software/Compiler/Maven/index.md
    - 办公软件:
      - Office: Software/Office/Office/index.md
      - Adboe: Software/Office/Adobe/index.md
   
  - 系统:
    - Linux: System/Linux/index.md
    - Windows: System/Windows/index.md
    - 虚拟机: System/Virtual_Machine/index.md

  - 资源:
    - 资源: Resource/index.md

  - 杂项:
    - 酒: MISC/Wine/index.md
    - 车: MISC/Car/index.md
    - 衣服: MISC/Clothes/index.md
    - 鞋子: MISC/Shoe/index.md

# [UI]界面

## [top] 顶部栏
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs     # 左侧出现分级目录
    # - navigation.expand   # 左侧分级目录缺省全部展开
    # - navigation.sections # 左侧分级目录不缩进区分
    - navigation.top      # 网页上滑出现一键返回顶部的按钮
    # - navigation.indexes  # 打开目录下的index.md，而不是第一篇文章第一篇文章
    - navigation.sticky   # 页面顶部横条导航栏
    - navigation.path     # 页面上部出现文件目录路径
    # - toc.integrate       # 右侧自动生成网页目录，否则自动整合入左侧分级目录
    - search.suggest      # 搜索输入一些字母时推荐补全整个单词
    - search.highlight    # 搜索出的文章关键词加入高亮
    - content.code.copy   # 代码块区域出现代码复制按钮
    - content.action.edit # 网页中显示编辑按钮, 点击按钮跳转到编辑页面
                          # 需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs  # 电极编辑按钮跳转的链接


## [top-right corner] 右上角落
repo_url: https://github.com/xcluo/xcluo.github.io  # 右上角点击跳转的链接
repo_name: xcluo.github.io                          # 右上角显示的名字

 
## [bottom-left corner] 左下角落
copyright: Powered by xcluo                         # 版权声明


## [bottom-right corner] 右下角落
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/24502827
      name: Bilibili                                # 鼠标悬浮提示文本
    - icon: fontawesome/brands/github
      link: https://github.com/xcluo
      name: GitHub | xcluo                          # 鼠标悬浮提示文本


# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - glightbox


markdown_extensions:
  - attr_list
  - pymdownx.tasklist:        # todo list
      custom_checkbox: true
  - md_in_html
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示代码块中代码行号
      # auto_title: true # 显示代码块编程语言名
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要


extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - packages/mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  # katex
  - packages/mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
# extra_css:
  - packages/mkdocs/css/no-footer.css # 不使用底部的翻页
  - packages/mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
