name: publish site
on: # 在什么时候触发工作流
  push: # 在从本地main分支被push到GitHub仓库时
    branches:
      - main
  pull_request: # 在main分支合并别人提的pr时
    branches:
      - main
jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v2 # 先checkout到main分支
      - uses: actions/setup-python@v2 # 再安装Python3和相关环境
        with:
          python-version: 3.x
      - run: pip install mkdocs-material  # 安装mkdocs-material
      - run: pip install mkdocs-glightbox # 安装mkdocs-glightbox
      - run: pip install jieba            # 安装jieba用于中文关键词搜索
      - run: mkdocs gh-deploy --force     # 使用mkdocs-material部署gh-pages分支